<a href="https://colab.research.google.com/github/parkmonty/W_Pile/blob/main/BDA_assignment(review_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 분석에 필요한 기초

In [7]:
# 리스트
a = ['사과', '딸기', '수박', '참외', '파인애플', '멜론']
# 2차원 리스트
b = [['사과', '딸기'], ['수박', '참외'], ['파인애플', '멜론']]

# 리스트를 접근하는 방법
for i in a:
  print(i)
print('----')
for j in range(len(a)):
  print(a[j])

# 2차원 리스트 접근 방법
print('\n<2차원 리스트>\n')

for i in range(len(b)):
  for j in range(len(b[i])):
    print(b[i][j])

사과
딸기
수박
참외
파인애플
멜론
----
사과
딸기
수박
참외
파인애플
멜론

<2차원 리스트>

사과
딸기
수박
참외
파인애플
멜론

*   2차원
*   가로와 세로 라는 공간
*   행렬의 개념
*   인덱스의 개념과 동일하게 접근이 되는 것
*   (0,0)(0,1)
*   (1,0)(1,1)
*   (2,0)(2,1)

*   데이터프레임의 개념으로 접근
*   2차원의 개념으로 행과 열
*   행은 인덱스, 열은 컬럼이 된다.


*   데이터프레임을 불러오기 위해서는
*   **pandas 가장 많이 사용** : 데이터프레임, 시리즈 구조 데이터를 가공, 전처리 하는 패키지, 금융데이터 처음 시작되었음
*   **numpy 많이 사용** : 공학적인 수학 관련 패키지들 연산이나 브로드캐스팅 등 다양하게 대용량 데이터를 쉽게 처리할 수 있음

In [8]:
# pandas, numpy 설치
# !pip install pandas
# !pip install numpy

import pandas as pd
import numpy as np
import seaborn as sns

# 변수 & 패키지

In [13]:
# 패키지를 이용해서 데이터 불러오기
df = sns.load_dataset('titanic')
# 필요한 컬럼만 모으기
df[['survived', 'pclass', 'sex', 'fare', 'class']]

     survived  pclass     sex     fare   class
0           0       3    male   7.2500   Third
1           1       1  female  71.2833   First
2           1       3  female   7.9250   Third
3           1       1  female  53.1000   First
4           0       3    male   8.0500   Third
..        ...     ...     ...      ...     ...
886         0       2    male  13.0000  Second
887         1       1  female  30.0000   First
888         0       3  female  23.4500   Third
889         1       1    male  30.0000   First
890         0       3    male   7.7500   Third

[891 rows x 5 columns]

# **데이터 프레임 만들기**

In [14]:
# 컬럼만 리스트로 모으기
df_col = list(df.columns)
df_col

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [15]:
# range함수를 이용해 슬라이싱 하는 개념과 동일
# 인덱스와 컬럼으로 추가해서 잡을 수 있음
df.loc[:100, 'survived']

0      0
1      1
2      1
3      1
4      0
      ..
96     0
97     1
98     1
99     0
100    0
Name: survived, Length: 101, dtype: int64

# **데이터 직접 만들기**

In [16]:
# pandas가 데이터 프레임을 만들과 전처리할 수 있는 좋은 패키지
df_sp = pd.DataFrame({'제품명' : ['과자', '세제', '사과', '물티슈'],
                      '가격' : [2500, 4000, 6000, 1500],
                      '재고' : [5, 8, 12, 10]})

In [20]:
# 판다스는 쉽게 전처리 가능
# 가격의 총합
print(sum(df_sp['가격']))
# 가격의 평균
print(sum(df_sp['가격']) / len(df_sp['가격']))

14000
3500.0

In [21]:
# 데이터 프레임 출력
df_sp

   제품명    가격  재고
0   과자  2500   5
1   세제  4000   8
2   사과  6000  12
3  물티슈  1500  10

In [22]:
# 1차원은 시리즈로 변환됨
# 판다스에서 제공하는 시리즈 형태
df_sp['가격']

0    2500
1    4000
2    6000
3    1500
Name: 가격, dtype: int64

# **실제 데이터 불러오기**


*   내가 만든 엑셀데이터
*   내가 만든 csv데이터 불러오기 가능
*   판다스에서 불러 올 수 있음

*   데이터의 위치가 중요하다.
*   데이터를 불러오려면 데이터가 존재하는 위치가 어디인지 정확하게 알고 있어야 한다.
*   read_csv, read_excel 불러올 수 있다.
*   판다스가 유용하지만 문제는 메모리를 만이 잡아 먹는다.

In [24]:
df_ex = pd.read_excel('excel_exam.xlsx')

# **데이터 분석을 진행해 보자!**
*   분석에 대한 목적이 정확해야 데이터의 분석을 시작할 수 있음
*   데이터베이스 안에 여러 테이블이 존재하면 보이지도 않은 테이블 가지고 분석 고민해야 하는 것들이 어렵다.
*   목적이 있는 분석
*   시각화 -> 나의 데이터 분석 주장을 뒷받침하는 근거를 탄탄하게 만들어 주는 것
-------------------------------------------
*   데이터를 분석할 때
*   info
*   데이터 타입과 데이터의 누락값, 결측치 확인 필수!
*   describe
*   요약통계의 개념
*   데이터 범주형, 연속형
*   데이터의 연속적인 데이터 -> 분포 확인 가능
*   정규분포인지 아니면 어떤 분포의 형태를 보이고 있는지
*   컬럼들이 어떤 식의 분포인지를 확인하는 기초적인 힌트를 주는 것

In [25]:
df_ex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 928.0 bytes

In [26]:
df_ex.describe()

             id     nclass       math    english    science
count  20.00000  20.000000  20.000000  20.000000  20.000000
mean   10.50000   3.000000  57.450000  84.900000  59.450000
std     5.91608   1.450953  20.299015  12.875517  25.292968
min     1.00000   1.000000  20.000000  56.000000  12.000000
25%     5.75000   2.000000  45.750000  78.000000  45.000000
50%    10.50000   3.000000  54.000000  86.500000  62.500000
75%    15.25000   4.000000  75.750000  98.000000  78.000000
max    20.00000   5.000000  90.000000  98.000000  98.000000

In [27]:
# 결측치를 꼭 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [29]:
df.describe(include = 'all')
# 데이터 분포가 한 쪽으로 쏠려 있거나, 정규분포가 아닌 형태일 것이다.
# 이상치가 존재할 것이다 라는 것을 확인

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN